p8105\_hw2\_jf3354
================
Judy Fordjuoh
October 2, 2021

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library(haven)
library(dplyr)
```

\#\#PROBLEM 1

``` r
TW_df = read_excel("MrTrash.xlsx", sheet = 'MrTrashWheel', range = 'A2:N408') %>%
    janitor::clean_names() %>%
    mutate(sports_balls = round(sports_balls)) %>%
    drop_na(dumpster) #dropping all the rows in dumpster that has a NA

TW19_df = TW_df %>%
  filter(year == "2019") %>%  
  select(year, sports_balls)
  
summary(TW19_df)
```

    ##       year       sports_balls   
    ##  Min.   :2019   Min.   : 0.000  
    ##  1st Qu.:2019   1st Qu.: 4.500  
    ##  Median :2019   Median : 8.500  
    ##  Mean   :2019   Mean   : 9.067  
    ##  3rd Qu.:2019   3rd Qu.:13.750  
    ##  Max.   :2019   Max.   :22.000

``` r
summary(TW_df)
```

    ##     dumpster         month                year     
    ##  Min.   :  1.00   Length:344         Min.   :2014  
    ##  1st Qu.: 86.75   Class :character   1st Qu.:2015  
    ##  Median :172.50   Mode  :character   Median :2017  
    ##  Mean   :172.50                      Mean   :2016  
    ##  3rd Qu.:258.25                      3rd Qu.:2018  
    ##  Max.   :344.00                      Max.   :2019  
    ##       date                      weight_tons    volume_cubic_yards
    ##  Min.   :2014-05-16 00:00:00   Min.   :0.960   Min.   : 7.00     
    ##  1st Qu.:2015-07-05 00:00:00   1st Qu.:2.757   1st Qu.:15.00     
    ##  Median :2017-03-31 00:00:00   Median :3.265   Median :15.00     
    ##  Mean   :2016-12-23 10:57:12   Mean   :3.263   Mean   :15.54     
    ##  3rd Qu.:2018-05-19 18:00:00   3rd Qu.:3.772   3rd Qu.:16.00     
    ##  Max.   :2019-06-17 00:00:00   Max.   :5.620   Max.   :20.00     
    ##  plastic_bottles   polystyrene   cigarette_butts  glass_bottles   
    ##  Min.   : 210.0   Min.   : 320   Min.   :   980   Min.   :  0.00  
    ##  1st Qu.: 957.5   1st Qu.:1065   1st Qu.:  7000   1st Qu.: 10.00  
    ##  Median :1835.0   Median :2075   Median : 19000   Median : 21.50  
    ##  Mean   :1873.2   Mean   :2139   Mean   : 30754   Mean   : 25.36  
    ##  3rd Qu.:2552.5   3rd Qu.:3120   3rd Qu.: 38000   3rd Qu.: 38.00  
    ##  Max.   :5960.0   Max.   :6540   Max.   :310000   Max.   :110.00  
    ##   grocery_bags    chip_bags       sports_balls   homes_powered  
    ##  Min.   :  50   Min.   : 230.0   Min.   : 0.00   Min.   : 0.00  
    ##  1st Qu.: 600   1st Qu.: 977.5   1st Qu.: 5.00   1st Qu.:35.62  
    ##  Median :1050   Median :1630.0   Median : 8.00   Median :51.42  
    ##  Mean   :1311   Mean   :1780.3   Mean   :11.81   Mean   :43.83  
    ##  3rd Qu.:1912   3rd Qu.:2490.0   3rd Qu.:16.00   3rd Qu.:59.50  
    ##  Max.   :3750   Max.   :5085.0   Max.   :56.00   Max.   :93.67

``` r
skimr::skim(TW_df)
```

|                                                  |        |
|:-------------------------------------------------|:-------|
| Name                                             | TW\_df |
| Number of rows                                   | 344    |
| Number of columns                                | 14     |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |        |
| Column type frequency:                           |        |
| character                                        | 1      |
| numeric                                          | 12     |
| POSIXct                                          | 1      |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |        |
| Group variables                                  | None   |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
|:---------------|-----------:|---------------:|----:|----:|------:|----------:|-----------:|
| month          |          0 |              1 |   3 |   9 |     0 |        12 |          0 |

**Variable type: numeric**

| skim\_variable       | n\_missing | complete\_rate |     mean |       sd |      p0 |     p25 |      p50 |      p75 |      p100 | hist  |
|:---------------------|-----------:|---------------:|---------:|---------:|--------:|--------:|---------:|---------:|----------:|:------|
| dumpster             |          0 |              1 |   172.50 |    99.45 |    1.00 |   86.75 |   172.50 |   258.25 |    344.00 | ▇▇▇▇▇ |
| year                 |          0 |              1 |  2016.50 |     1.58 | 2014.00 | 2015.00 |  2017.00 |  2018.00 |   2019.00 | ▇▃▃▆▂ |
| weight\_tons         |          0 |              1 |     3.26 |     0.75 |    0.96 |    2.76 |     3.26 |     3.77 |      5.62 | ▁▅▇▅▁ |
| volume\_cubic\_yards |          0 |              1 |    15.54 |     1.68 |    7.00 |   15.00 |    15.00 |    16.00 |     20.00 | ▁▁▁▇▂ |
| plastic\_bottles     |          0 |              1 |  1873.15 |  1028.87 |  210.00 |  957.50 |  1835.00 |  2552.50 |   5960.00 | ▇▆▅▁▁ |
| polystyrene          |          0 |              1 |  2138.68 |  1202.82 |  320.00 | 1065.00 |  2075.00 |  3120.00 |   6540.00 | ▇▆▅▁▁ |
| cigarette\_butts     |          0 |              1 | 30754.13 | 34492.50 |  980.00 | 7000.00 | 19000.00 | 38000.00 | 310000.00 | ▇▁▁▁▁ |
| glass\_bottles       |          0 |              1 |    25.36 |    18.64 |    0.00 |   10.00 |    21.50 |    38.00 |    110.00 | ▇▅▂▁▁ |
| grocery\_bags        |          0 |              1 |  1311.23 |   881.87 |   50.00 |  600.00 |  1050.00 |  1912.50 |   3750.00 | ▇▇▅▃▁ |
| chip\_bags           |          0 |              1 |  1780.27 |   956.53 |  230.00 |  977.50 |  1630.00 |  2490.00 |   5085.00 | ▇▇▅▂▁ |
| sports\_balls        |          0 |              1 |    11.81 |     9.81 |    0.00 |    5.00 |     8.00 |    16.00 |     56.00 | ▇▃▁▁▁ |
| homes\_powered       |          0 |              1 |    43.83 |    23.98 |    0.00 |   35.62 |    51.42 |    59.50 |     93.67 | ▅▂▇▆▁ |

**Variable type: POSIXct**

| skim\_variable | n\_missing | complete\_rate | min        | max        | median     | n\_unique |
|:---------------|-----------:|---------------:|:-----------|:-----------|:-----------|----------:|
| date           |          0 |              1 | 2014-05-16 | 2019-06-17 | 2017-03-31 |       217 |

``` r
prep_2019 = read_excel("MrTrash.xlsx", sheet = '2019 Precipitation',range = 'A2:B14') %>%
  drop_na() %>%
  mutate(year = "2019")
   
prep_2018 = read_excel("MrTrash.xlsx", sheet = '2018 Precipitation', range = 'A2:B14') %>%  
    mutate(year = "2018")
    
##I also got rid of the last row which was the total precipitations

precip18_19 = 
  bind_rows(prep_2019, prep_2018) %>%
  arrange(year,Month, Total) %>% 
  mutate(Month = month.name[Month]) 

summary(prep_2019)
```

    ##      Month          Total           year          
    ##  Min.   :1.00   Min.   :0.420   Length:6          
    ##  1st Qu.:2.25   1st Qu.:1.870   Class :character  
    ##  Median :3.50   Median :3.340   Mode  :character  
    ##  Mean   :3.50   Mean   :2.778                     
    ##  3rd Qu.:4.75   3rd Qu.:3.625                     
    ##  Max.   :6.00   Max.   :4.470

``` r
summary(precip18_19)
```

    ##     Month               Total            year          
    ##  Length:18          Min.   : 0.420   Length:18         
    ##  Class :character   1st Qu.: 2.792   Class :character  
    ##  Mode  :character   Median : 4.580   Mode  :character  
    ##                     Mean   : 4.833                     
    ##                     3rd Qu.: 6.365                     
    ##                     Max.   :10.470

``` r
skimr::skim(precip18_19)
```

|                                                  |              |
|:-------------------------------------------------|:-------------|
| Name                                             | precip18\_19 |
| Number of rows                                   | 18           |
| Number of columns                                | 3            |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |              |
| Column type frequency:                           |              |
| character                                        | 2            |
| numeric                                          | 1            |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |              |
| Group variables                                  | None         |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
|:---------------|-----------:|---------------:|----:|----:|------:|----------:|-----------:|
| Month          |          0 |              1 |   3 |   9 |     0 |        12 |          0 |
| year           |          0 |              1 |   4 |   4 |     0 |         2 |          0 |

**Variable type: numeric**

| skim\_variable | n\_missing | complete\_rate | mean |   sd |   p0 |  p25 |  p50 |  p75 |  p100 | hist  |
|:---------------|-----------:|---------------:|-----:|-----:|-----:|-----:|-----:|-----:|------:|:------|
| Total          |          0 |              1 | 4.83 | 3.04 | 0.42 | 2.79 | 4.58 | 6.36 | 10.47 | ▅▅▇▁▃ |

### Question: Write a paragraph about these data; you are encouraged to use inline R. Be sure to note the number of observations in both resulting datasets, and give examples of key variables. For available data, what was the total precipitation in 2018? What was the median number of sports balls in a dumpster in 2019?

Answer: After cleaning the Trash Wheel dataset (TW\_df), there was 344
observations and 14 variables. The mean weight in tons of the dumpsters
was 3.263 tons and there eas a mean of 15.54 for the volume by cubic
yards. The following are the means of items found in the dumpsters:
plasitc bottles = 1873.2, polystyrene = 2139, cig butts = 30754, glass
bottles = 25.36, grocery bags = 1311, chip bags = 1780.3, sports balls =
11.81.

After combining the precpitiation data from 2018 and 2019 into a new
dataframe (precip18\_19), I had 18 observations and 3 variables: month,
total, and year. The median total precipation was 4.580 while the mean
was 4.833.

The total precipitation in 2018 was 70.33. The median number of sports
balls in a dumpster in 2019 was 8.5 sports balls.

\#\#PROBLEM 2  
\#President: 1=Democrat 0=Repubs

``` r
p_m = read_csv("pols-month.csv") %>%
  separate(mon, c("year", "Month", "Day")) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(Month = month.name[as.numeric(Month)]) %>%
  mutate(president = ifelse(is.na(prez_dem), prez_gop, prez_dem )) %>%
  select(-prez_dem, -prez_gop, -Day)
```

    ## Rows: 822 Columns: 9

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
s_np = read_csv("snp.csv") %>%
  separate(date, c("Day", "Month", "year")) %>%
  mutate(year = as.numeric(year)) %>%
  mutate(year = if_else(year >= 50,
                        year + 1900,
                        year + 2000)) %>%
  arrange(year,Month) %>% 
  mutate(Month = (month.name[as.numeric(Month)])) %>%
  select(year, Month, everything()) 
```

    ## Rows: 787 Columns: 2

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pmsnp_df1 = 
  left_join(p_m, s_np, by = c("year", "Month"))

un_emp = read_csv("unemployment.csv") 
```

    ## Rows: 68 Columns: 13

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
un_emp_tidy = un_emp %>%
  pivot_longer(
    Jan:Dec, 
    names_to = 'Month',
    values_to = 'Percentage'
  ) %>%
  mutate(
    Month = recode(Month, 
         Jan = "January",
         Feb = "February",
         Mar = "March",
         Apr = "April",
         Jun = "June",
         Jul = "July",
         Aug = "August",
         Sep = "September",
         Oct = "October",
         Nov = "November",
         Dec = "December")
  ) %>%
  rename(year = Year)

finalQ2_df = 
  left_join(pmsnp_df1, un_emp_tidy, by = c("year", "Month"))
```

\#\#Write a short paragraph about these datasets. Explain briefly what
each dataset contained, and describe the resulting dataset (e.g. give
the dimension, range of years, and names of key variables).

\#\#PROBLEM 3

``` r
pbn = read_csv("Popular_Baby_Names.csv") %>%
  distinct() %>% 
  janitor::clean_names() %>%
  mutate(childs_first_name = toupper(childs_first_name)) %>%
  mutate(
    ethnicity = recode(ethnicity, 
         "ASIAN AND PACI" = "ASIAN AND PACIFIC ISLANDER",
         "BLACK NON HISP" = "BLACK NON HISPANIC",
         "WHITE NON HISP" = "WHITE NON HISPANIC"
        )) 
```

    ## Rows: 19418 Columns: 6

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Gender, Ethnicity, Child's First Name
    ## dbl (3): Year of Birth, Count, Rank

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
olivia_pbn = pbn %>%
filter(childs_first_name == "OLIVIA") %>%  
select(-gender, -childs_first_name, -count) %>%
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "rank") %>%
relocate(ethnicity, "2011","2012","2013","2014","2015")
```

``` r
#table for the MALES
#filter(pbn, gender == "MALE", rank == "1", year_of_birth == "2010")
#After filtering the dataset by gender (Male), rank (1), and by year (ran individually from year 2011-2016), the name Jayden was ranked first at least by one ethnicity from the years 2011-2015 which makes it the most popular name in this dataset.

jayden_pbn = pbn %>%
filter(childs_first_name == "JAYDEN") %>%  
select(-gender, -childs_first_name, -count) %>%
  pivot_wider(
    names_from = "year_of_birth",
    values_from = "rank") %>%
relocate(ethnicity, "2011","2012","2013","2014","2015")
```

``` r
babynamef = filter(pbn, gender == "MALE", ethnicity == "WHITE NON HISPANIC", year_of_birth == "2016") 
p <- ggplot(babynamef , aes(x = rank, y = count)) +   geom_point(alpha = 0.5) + ggtitle("Popular Names in White Non-Hispanic Male Children, 2016") 

print(p)
```

![](p8105_HW2_jf3354_files/figure-gfm/unnamed-chunk-7-1.png)<!-- -->

``` r
ggsave("JF_DSHW2_scatterplot.pdf", height = 10, width = 6)
```
